---
version: "2"
services:
  
  # LDAP Server on
  ldap-host:
    image: "osixia/openldap:1.1.8"
    restart: always
    environment:
      LDAP_ORGANISATION: "ARNTS Labs"
      LDAP_DOMAIN: "${DOMAIN}"
      LDAP_ADMIN_PASSWORD: "${PASS}"
    volumes:
        - ${LDAP_DB}:/var/lib/ldap:rw
        - ${LDAP_CONF}/ldap/config:/etc/ldap/slapd.d:rw
    networks:
      LAN:
        ipv4_address: "${NET}.22"
    hostname: ldap-host
  
  # LDAP Web GUI on 172.16.10.3
  ldap-gui: 
    image: "osixia/phpldapadmin:0.6.12"
    links:
      - ldap-host
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-host
    networks:
      LAN:
        ipv4_address: "${NET}.23"
    hostname: ldap-gui

  # DNS/DHCP Server
  dhcpdns: 
    image: "mayankt/dhcpdns"
    restart: always
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    volumes:
        - ${DNS_DATA}:/data:rw
        #- ${DHCP_CONF}:/etc/dhcp/dhcpd.conf:rw
    networks:
      LAN:
        ipv4_address: "${NET}.24"
    hostname: dhcpdns


  # Guacamole service for Robust Backdoor access
  guacamole:
    image: db260179/guacamole-combined
    restart: always
    volumes:
      - ${GUAC_DATA}:/app/data
    networks:
      LAN:
        ipv4_address: "${NET}.25"
    hostname: guacamole
  
  # XenOrchestra service for Host communication
  xenorchstra:
    image: yobasystems/alpine-xen-orchestra:latest
    links:
      - redis
    volumes:
      - ${XO_DATA}:/app/data
    networks:
      LAN:
        ipv4_address: "${NET}.26"
      private:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DATA}:/data
    networks:
      private:

  # IPAM service for network IP mgmgt
  mariadb:
    image: mariadb:latest
    volumes:
      - "${IPAM_SQL}:/var/lib/mysql:rw"
    environment:
      - MYSQL_ROOT_PASSWORD=${PASS}
      - MYSQL_DATABASE=phpipam
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${PASS}
    restart: always
    networks:
      private:
    hostname: mariadb
  phpipam:
    image: rafpe/docker-phpipam
    environment:
      - MYSQL_DB_HOSTNAME=mariadb
      - MYSQL_DB_USERNAME=root
      - MYSQL_DB_PASSWORD=${PASS}
      - MYSQL_DB_NAME=phpipam
      - MYSQL_DB_PORT=3306
    restart: always
    depends_on:
      - mariadb
    networks:
      LAN:
        ipv4_address: "${NET}.27"
      private:
    hostname: redis

  # Simple Backend WebServers
  webserver-a:
    image: mayankt/webserver:a
    restart: always
    networks:
        LAN:
          ipv4_address: "${NET}.28"
    hostname: webserver-a
  webserver-b:
    image: mayankt/webserver:b
    restart: always
    networks:
        LAN:
          ipv4_address: "${NET}.29"
    hostname: webserver-b

  # Docker UI for container management
  portainer:
    image: portainer/portainer
    restart: always
    networks:
        LAN:
          ipv4_address: "${NET}.30"
    hostname: Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

  #WebGoat for Application Firewall Demos
  webgoat:
    image: webgoat/webgoat-8.0
    restart: always
    networks:
        LAN:
          ipv4_address: "${NET}.31"
    hostname: Portainer

# Defined networks
networks:
  # define a host-external network (assuming eth0 is the interface you want to share)
  LAN:
    driver: macvlan
    driver_opts:
      parent: "${ETH}"
    ipam:
      config:
        - subnet: "${NET}.0/24"
          gateway: "${GATEWAY}"
          ip_range: "${NET}.35/28" # IP from this pool are assigned automatically (172.16.10.12-172.16.10.26 
  private:
    driver: bridge